apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app
  namespace: default 
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-one
  path: ./apps
  prune: true
