apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: springboot-jib
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./springboot-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
